Repository sprint-team3/GGF-Design-System, pull requests merged in 2024-04, with the labels that each got.

#1 Refactor: 탭 컴포넌트 리팩토링
  src/components/Tab/index.tsx
Labels: 리팩토링

#2 Refactor: 필터 컴포넌트 리팩토링
  src/components/Filter/index.tsx
Labels: 리팩토링

#8 Refactor: Avatar 컴포넌트 리팩토링
  src/components/Avatar/index.tsx
Labels: 리팩토링

#9 Refactor: Pagination 컴포넌트 리팩토링
  src/components/Pagination/index.tsx
Labels: 리팩토링

#13 Refactor: InputRadio 리팩토링
  src/components/inputs/InputRadio.tsx
Labels: 리팩토링

#18 Refactor: TextField 리팩토링
  src/components/inputs/TextField.tsx
Labels: 리팩토링

#22 Refactor: 버튼의 theme 프롭 이름을 variant로 변경
  src/components/buttons/BaseButton.tsx
Labels: 리팩토링

#24 Refactor: Card 리팩토링
  src/components/cards/Card.tsx
Labels: 리팩토링

#25 Refactor: Badge 리팩토링
  src/components/Badge/index.tsx
Labels: 리팩토링

#26 Refactor: Tag 리팩토링
  src/components/Tag/index.tsx
Labels: 리팩토링

#29 Hotfix: tsx에서 제네릭 태그 인식 못하는 오류 수정
  src/components/Filter/index.tsx
  src/components/Tab/index.tsx
Labels: 버그 해결

#28 Refactor: 버튼 이미지 import 수정 및 import order 적용
  src/components/buttons/CountButton.tsx
  src/components/buttons/MoreButton.tsx
  src/components/buttons/OperationButton.tsx
  src/components/buttons/SliderButton.tsx
Labels: 리팩토링

#30 Refactor: ImageField import문 수정
  src/components/inputs/ImageField.tsx
Labels: 리팩토링

#32 Refactor: InputRadio color props로 추가
  src/components/inputs/InputRadio.module.scss
  src/components/inputs/InputRadio.tsx
Labels: 리팩토링

#35 Refactor: SearchBar color props로 받도록 수정
  src/components/inputs/SearchBar.module.scss
  src/components/inputs/SearchBar.tsx
Labels: 리팩토링

#38 Refactor: 사용하지 않는 constants 파일 삭제
  src/constants/apiPaths.ts
  src/constants/auth.ts
  src/constants/breakPoint.ts
  src/constants/date.ts
  src/constants/faqList.ts
  src/constants/games.ts
  src/constants/index.ts
  src/constants/initialData.ts
  src/constants/inputNames.ts
  src/constants/inputValidation.ts
  src/constants/metaData.ts
  src/constants/myReservationsStatus.ts
  src/constants/pagePaths.ts
  src/constants/paging.ts
  src/constants/postForm.ts
  src/constants/postList.ts
  src/constants/postTypes.ts
  src/constants/prompt.ts
  src/constants/radioOptions.ts
  src/constants/sortOptions.ts
  src/constants/tapOptions.ts
  src/constants/times.ts
Labels: 리팩토링

#40 Feat: Button/Filter/Tab 컴포넌트 스토리북 추가
  src/stories/BaseButton.stories.ts
  src/stories/CardButton.stories.ts
  src/stories/CountButton.stories.ts
  src/stories/Filter.stories.ts
  src/stories/MoreButton.stories.ts
  src/stories/OperationButton.stories.ts
  src/stories/Tab.stories.ts
Labels: UI 구현

#43 Feat: EmptyCard 추가
  src/components/EmptyCard/EmptyCard.module.scss
  src/components/EmptyCard/index.tsx
  src/stories/EmptyCard.stories.ts
Labels: UI 구현

#45 Refactor: AlarmList/HeaderProfile/UseMenu의 prop 수정
  src/components/header/AlarmList/index.tsx
  src/components/header/HeaderProfile/index.tsx
  src/components/header/UserMenu/index.tsx
Labels: 리팩토링

#48 Refactor: Pagination 컴포넌트에 pageLimit prop 추가
  src/components/Pagination/index.tsx
Labels: 리팩토링

#44 Feat: Countbutton 최소값 없을시 0으로 세팅
  src/components/buttons/CountButton.tsx
Labels: 기능 구현

#46 Fix: 필터/탭 컴포넌트 클릭시 활성화되도록 수정
  src/components/Filter/index.tsx
  src/components/Tab/index.tsx
Labels: 버그 해결

#51 Refactor: InputRadio color optional prop으로 변경
  src/components/inputs/InputRadio.tsx
Labels: 리팩토링

#52 Feat: chromatic workflows
  .github/workflows/chromatic
Labels: 기능 구현

#58 Refactor: FormDropdown nesting 문법 적용
  src/components/inputs/FormDropdown.module.scss
  src/components/inputs/FormDropdown.tsx
Labels: 리팩토링

#59 Refactor: InputRadio nesting 문법 적용
  src/components/inputs/InputRadio.module.scss
  src/components/inputs/InputRadio.tsx
Labels: 리팩토링

#60 Refactor: img import 수정 테스트
  src/components/inputs/SearchBar.tsx
Labels: 리팩토링

#62 Refactor: Basebutton 넘치는 텍스트 ellipsis (...) 처리
  src/components/buttons/BaseButton.module.scss
Labels: 리팩토링

#63 Refactor: Badge 리팩토링
  src/components/Badge/index.tsx
Labels: 리팩토링

#66 Refactor: Card 리팩토링
  src/stories/Card.stories.ts
  src/stories/ReviewCard.stories.ts
Labels: 리팩토링

#70 Refactor: SearchBar 이미지 경로 수정
  src/components/inputs/SearchBar.tsx
Labels: 리팩토링

#74 Hotfix: package script 수정
  package.json
Labels: 리팩토링

#76 Refactor: 버튼/필터/탭 컴포넌트 폴더구조 변경
  src/lib/components/BaseButton/BaseButton.module.scss
  src/lib/components/BaseButton/BaseButton.tsx
  src/lib/components/BaseButton/index.ts
  src/lib/components/CardButton/CardButton.module.scss
  src/lib/components/CardButton/CardButton.tsx
  src/lib/components/CardButton/index.ts
  src/lib/components/CountButton/CountButton.module.scss
  src/lib/components/CountButton/CountButton.tsx
  src/lib/components/CountButton/index.ts
  src/lib/components/Filter/Filter.tsx
  src/lib/components/Filter/index.ts
  src/lib/components/MoreButton/MoreButton.module.scss
  src/lib/components/MoreButton/MoreButton.tsx
  src/lib/components/MoreButton/index.ts
  src/lib/components/OperationButton/OperationButton.module.scss
  src/lib/components/OperationButton/OperationButton.tsx
  src/lib/components/OperationButton/index.ts
  src/lib/components/SliderButton/SliderButton.module.scss
  src/lib/components/SliderButton/SliderButton.tsx
  src/lib/components/SliderButton/index.ts
  src/lib/components/Tab/Tab.tsx
  src/lib/components/Tab/index.ts
  src/lib/components/buttons/index.ts
  src/lib/stories/BaseButton.stories.ts
  src/lib/stories/CardButton.stories.ts
  src/lib/stories/CountButton.stories.ts
  src/lib/stories/MoreButton.stories.ts
  src/lib/stories/OperationButton.stories.ts
Labels: 리팩토링

#79 Refactor: package.json 라이브러리 정보 등록 및 compile script 추가
  package-lock.json
  package.json
Labels: 환경

#80 Hotfix: ImageField의 ConfirmModal과 ModalButton import 경로 수정
  src/lib/components/ImageField/ImageField.tsx
Labels: ASAP, 버그 해결

#81 Feat: 라이브러리 컴포넌트, style, util index에서 export
  src/lib/index.ts
Labels: 기능 구현

#82 HotFix: BaseButton 텍스트 중앙정렬 안맞는 오류 수정
  src/lib/components/BaseButton/BaseButton.module.scss
Labels: 버그 해결

#83 Hotfix: 필터, 탭 컴포넌트 font weight 수정
  src/lib/components/Filter/Filter.module.scss
  src/lib/components/Tab/Tab.module.scss
Labels: 버그 해결

#87 Chore: chromatic.yml 생성
  .github/workflows/chromatic.yml
Labels: 문서

#92 Hotfix: 이미지 안나오는 오류 해결
  public/assets/ic-add-active.svg
  public/assets/ic-add.svg
  public/assets/ic-alarm-empty.svg
  public/assets/ic-alarm-full.svg
  public/assets/ic-alarm-off.svg
  public/assets/ic-arrow-bottom.svg
  public/assets/ic-arrow-down-active.svg
  public/assets/ic-arrow-down-default.svg
  public/assets/ic-arrow-left-active.svg
  public/assets/ic-arrow-left-default.svg
  public/assets/ic-arrow-right-active.svg
  public/assets/ic-arrow-right-default.svg
  public/assets/ic-arrow-top.svg
  public/assets/ic-button-border-active.svg
  public/assets/ic-button-border.svg
  public/assets/ic-calendar-active.svg
  public/assets/ic-calendar-default.svg
  public/assets/ic-chat.svg
  public/assets/ic-chatbot-sad.svg
  public/assets/ic-chatbot.svg
  public/assets/ic-chevron.svg
  public/assets/ic-close-active.svg
  public/assets/ic-close-default.svg
  public/assets/ic-discord.svg
  public/assets/ic-doubleArrow-left.svg
  public/assets/ic-doubleArrow-right.svg
  public/assets/ic-empty-paper.svg
  public/assets/ic-eye-off.svg
  public/assets/ic-eye-on.svg
  public/assets/ic-frame.svg
  public/assets/ic-location-active.svg
  public/assets/ic-location-default.svg
  public/assets/ic-map-active.svg
  public/assets/ic-menu.svg
  public/assets/ic-more.svg
  public/assets/ic-profile.svg
  public/assets/ic-remove-active.svg
  public/assets/ic-remove.svg
  public/assets/ic-search.svg
  public/assets/ic-send.svg
  public/assets/ic-setting.svg
  public/assets/ic-singleArrow-left.svg
  public/assets/ic-singleArrow-right.svg
  public/assets/ic-star-empty.svg
  public/assets/ic-star-error.svg
  public/assets/ic-star-filled.svg
  public/assets/ic-trashcan-hover.svg
  public/assets/ic-trashcan-normal.svg
  public/assets/ic-upload-active.svg
  public/assets/ic-upload-default.svg
  public/assets/ic-upload-file.svg
  src/lib/constants/images.ts
Labels: 버그 해결

#94 Chore: 빌드 경로 세팅 플러그인 추가
  package-lock.json
  package.json
  vite.config.ts
Labels: 기능 구현

#97 Feat: 필터 컴포넌트 배경색 추가
  src/lib/components/Filter/Filter.module.scss
Labels: 리팩토링

#100 Hotfix: 패키지 버전 업데이트
  package-lock.json
  package.json
Labels: 환경

#112 Refactor: InputField 리팩토링
  src/lib/components/InputField/InputField.tsx
Labels: 리팩토링

#113 Docs: 컴포넌트 사용 예시 수정
  docs/BaseButton.mdx
  docs/CardButton.mdx
  docs/EmptyCard.mdx
  docs/ModalButton.mdx
  docs/OperationButton.mdx
  docs/SliderButton.mdx
Labels: 문서

#114 Hotfix: InputField input에 color classname 추가
  src/lib/components/InputField/InputField.tsx
Labels: ASAP, 버그 해결

#116 Docs: SliderButton 설명란 수정 및 스토리북 추가
  docs/SliderButton.mdx
  src/stories/SliderButton.stories.ts
Labels: 문서

#117 Refactor: README 이미지 경로 변경
  README.md
Labels: 문서
